### ISSUE TITLE
Arrays subscription firing despite not being changed?  

### ISSUE THREAD

**Issue by Swoorup** [bryanmylee/svelte-keyed#7]
Not sure if this is a bug, but looks undesired behavior and unnecessary? When I change the name here, the name subscriber is triggered and the age subscriber isn't triggered. 

But why does the book subscriber trigger though?

```typescript
  const profile = writable({
    name: "swoorup",
    age: 12,
    books: [
      'd', 'asd'
    ]
  });

  const name = keyed(profile, "name");
  const age = keyed(profile, "age");
  const books = keyed(profile, "books");

  name.subscribe(n => console.log(`Name changed: ${n}`));
  age.subscribe(a => console.log(`Age changed: ${a}`));
  books.subscribe(a => console.log(`Books changed: ${a}`));

  console.log("Changing name");
  name.set("john");

  /*
    Name changed: john
    Books changed: d,asd // why does books changed here?
  */

```

**Comment by Swoorup** [comment]
Ah looks more like a svelte library thing. I can see under the hood its just using derived.

**Comment by bryanmylee** [comment]
@Swoorup Hey yep! Unfortunately this is how the `derived` store works. It only does a simple `===` check and does not handle object or array comparisons, most likely due to performance reasons.
